/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controll.Controller;

import javax.swing.*;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;

/**
 *
 * @author Dell
 */
public class ProjectsFrame extends JFrame implements ActionListener , ListSelectionListener {

    /**
     * Creates new form NewJFrame
     */
    public ProjectsFrame() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jLabel1 = new JLabel();
        jScrollPane1 = new JScrollPane();

        jTable1 = new JTable();
        jTable1.getSelectionModel().addListSelectionListener(this);

        jButton1 = new JButton();
        jButton2 = new JButton();
        jLabel2 = new JLabel();
        jLabel3 = new JLabel();
        jLabel4 = new JLabel();
        jLabel5 = new JLabel();
        jLabel6 = new JLabel();
        invNumLbl = new JLabel();
        invDateTF = new JTextField();
        cusNameTF = new JTextField();
        invTotalLb = new JLabel();
        jLabel7 = new JLabel();
        jScrollPane2 = new JScrollPane();
        jTable2 = new JTable();
        jButton3 = new JButton();
        jButton4 = new JButton();
        jMenuBar1 = new JMenuBar();
        jMenu1 = new JMenu();
        saveMenuItem = new JMenuItem();
        saveMenuItem.setActionCommand("Save File");
        saveMenuItem.addActionListener (this);

        loadMenuItem = new JMenuItem();
        loadMenuItem.setActionCommand("Load File");
        loadMenuItem.addActionListener (this);
        jMenu2 = new JMenu();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Invoices Table");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null}
                },
                new String [] {
                        "No.", "Date ", "Customer", "Total"
                }
        ));
        jTable1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Create New Invoice");
        jButton1.setActionCommand("Create New Invoice");
        jButton1.addActionListener (this);
        jButton1.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });


        jButton2.setText("Delete Invoice");
        jButton2.setActionCommand("Delete Invoice");
        jButton2.addActionListener (this);

        jLabel2.setText("Invoice Items Table");

        jLabel3.setText("Invoice No.");

        jLabel4.setText("Invoice Date");

        jLabel5.setText("Customer");

        jLabel6.setText("Invoice Total");

        invNumLbl.setText("");

        cusNameTF.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                cusNameTFActionPerformed(evt);
            }
        });

        jLabel7.setText("Invoice Items");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {null, null, null, null, null},
                        {null, null, null, null, null},
                        {null, null, null, null, null},
                        {null, null, null, null, null}
                },
                new String [] {
                        "No.", "Item Name", "Item Price", "Count", "Total"
                }
        ));
        jTable2.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        jScrollPane2.setViewportView(jTable2);

        jButton3.setText("Add New Item");
        jButton3.setActionCommand("Add Item");
        jButton3.addActionListener (this);
        jButton3.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Delete Item");
        jButton4.setActionCommand("Delete Item");
        jButton4.addActionListener (this);

        jMenu1.setText("File");

        saveMenuItem.setText("Save File");
        jMenu1.add(saveMenuItem);

        loadMenuItem.setText("Load File");
        loadMenuItem.setToolTipText("");
        loadMenuItem.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                loadMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(loadMenuItem);

        jMenuBar1.add(jMenu1);
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(24, 24, 24)
                                                .addComponent(jButton1)
                                                .addGap(41, 41, 41)
                                                .addComponent(jButton2)
                                                .addGap(155, 155, 155)
                                                .addComponent(jButton3)
                                                .addGap(43, 43, 43)
                                                .addComponent(jButton4)
                                                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel1)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(10, 10, 10)
                                                                .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 324, GroupLayout.PREFERRED_SIZE)))
                                                .addGap(36, 36, 36)
                                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel2)
                                                                .addGap(0, 0, Short.MAX_VALUE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jScrollPane2, GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                                                .addContainerGap())
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(jLabel5, GroupLayout.PREFERRED_SIZE, 76, GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(cusNameTF, GroupLayout.PREFERRED_SIZE, 257, GroupLayout.PREFERRED_SIZE))
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(jLabel3, GroupLayout.PREFERRED_SIZE, 74, GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(invNumLbl))
                                                                        .addComponent(jLabel7))
                                                                .addContainerGap())
                                                        .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                .addGap(0, 0, Short.MAX_VALUE)
                                                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                                        .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                                .addComponent(invTotalLb, GroupLayout.PREFERRED_SIZE, 55, GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(211, 211, 211))
                                                                        .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(jLabel4, GroupLayout.PREFERRED_SIZE, 76, GroupLayout.PREFERRED_SIZE)
                                                                                        .addComponent(jLabel6, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 76, GroupLayout.PREFERRED_SIZE))
                                                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(invDateTF, GroupLayout.PREFERRED_SIZE, 257, GroupLayout.PREFERRED_SIZE)
                                                                                .addContainerGap())))))))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel1))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                                        .addComponent(invNumLbl)
                                                        .addComponent(jLabel3, GroupLayout.PREFERRED_SIZE, 18, GroupLayout.PREFERRED_SIZE))
                                                .addGap(14, 14, 14)
                                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel4, GroupLayout.PREFERRED_SIZE, 20, GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(invDateTF, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel5)
                                                        .addComponent(cusNameTF, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel6, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(invTotalLb)
                                                .addGap(46, 46, 46)
                                                .addComponent(jLabel7)
                                                .addGap(18, 18, 18)
                                                .addComponent(jScrollPane2, GroupLayout.PREFERRED_SIZE, 203, GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 401, GroupLayout.PREFERRED_SIZE))
                                .addGap(11, 11, 11)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jButton1)
                                                        .addComponent(jButton2))
                                                .addGap(57, 57, 57))
                                        .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jButton3)
                                                        .addComponent(jButton4))
                                                .addGap(42, 42, 42))))
        );

        pack();
    }// </editor-fold>

    public void jButton1ActionPerformed(ActionEvent evt) {
        // TODO add your handling code here:
    }

    public void cusNameTFActionPerformed(ActionEvent evt) {
        // TODO add your handling code here:
    }

    public void jButton3ActionPerformed(ActionEvent evt) {
        // TODO add your handling code here:
    }

    public void loadMenuItemActionPerformed(ActionEvent evt) {
        // TODO add your handling code here:
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProjectsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProjectsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProjectsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProjectsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProjectsFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private JTextField cusNameTF;
    private JTextField invDateTF;
    private JLabel invNumLbl;
    private JLabel invTotalLb;
    private JButton jButton1;
    private JButton jButton2;
    private JButton jButton3;
    private JButton jButton4;
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private JLabel jLabel4;
    private JLabel jLabel5;
    private JLabel jLabel6;
    private JLabel jLabel7;
    private JMenu jMenu1;
    private JMenu jMenu2;
    private JMenuBar jMenuBar1;
    private JScrollPane jScrollPane1;
    private JScrollPane jScrollPane2;
    private JTable jTable1;
    private JTable jTable2;
    private JMenuItem loadMenuItem;
    private JMenuItem saveMenuItem;
    // End of variables declaration

    private Controller controller;

    @Override
    public void actionPerformed(ActionEvent e) {
        if (e.getActionCommand().equals("Load File")){

            try {
//                loadFiles();
                controller = new Controller(this);
                controller.loadFiles();

            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
        else if(e.getActionCommand().equals("Save File")){
            try {
                controller.saveDataInHeader();

            } catch (Exception ex) {
                ex.printStackTrace();
            }
            try {
                controller.saveDataInLines();

            } catch (IOException ex) {
                ex.printStackTrace();
            }
        }

        else if(e.getActionCommand().equals("Create New Invoice")){
            controller.createInvoice();
        }

        else if(e.getActionCommand().equals("Create Invoice Ok")){
            controller.createInvoiceOk();
        }

        else if(e.getActionCommand().equals("Create Invoice Cancel")){
            controller.createInvoiceCancel();
        }

        else if (e.getActionCommand().equals("Delete Invoice")){
            controller.deleteInvoice();

        }

        else if (e.getActionCommand().equals("Add Item")){
            controller.addNewItem();
        }

        else if (e.getActionCommand().equals("Add new Item OK")){
            controller.addNewItemOk();
        }

        else if (e.getActionCommand().equals("Add New Item Cancel")){
            controller.cancelAddingNewItem();
        }

        else if (e.getActionCommand().equals("Delete Item")){
            controller.deleteItem();

        }
    }


    @Override
    public void valueChanged(ListSelectionEvent e) {
        controller.jTable1RowSelected();
    }

    public JTable getjTable1() {
        return jTable1;
    }

    public JTable getjTable2() {
        return jTable2;
    }

    public JTextField getCusNameTF() {
        return cusNameTF;
    }

    public JTextField getInvDateTF() {
        return invDateTF;
    }

    public JLabel getInvNumLbl() {
        return invNumLbl;
    }

    public JLabel getInvTotalLb() {
        return invTotalLb;
    }
}